getwd()
library(tidyverse)
storm<- read.csv(file = "StormEvents_details-ftp_v1.0_d1998_c20220425.csv")
view(storm)
head(storm,10)
df <- storm %>% select(BEGIN_DATE_TIME, END_DATE_TIME, EPISODE_ID, EVENT_ID, STATE,
                    STATE_FIPS, CZ_NAME, CZ_TYPE, CZ_FIPS, EVENT_TYPE, SOURCE,
                    BEGIN_LAT, BEGIN_LON, END_LAT, END_LON)
head(df)
arrange(df,STATE)
str_to_title(df$STATE, locale = "en")
str_to_title(df$CZ_NAME, locale = "en")
filter(df, CZ_TYPE=="C")
select(df,-c(CZ_TYPE))
str_pad(df$STATE_FIPS, width = 3, side="left",pad="0")
str_pad(df$CZ_FIPS, width = 3, side="left",pad="0")
unite(df,CZ_FIPS, STATE_FIPS, remove = TRUE)
rename_all(df, tolower)
data("state")
us_state_info <-data.frame(state=state.name, region=state.region, area=state.area)
table(df$STATE)
newset<-data.frame(table(df$STATE))
head(newset)
newset<-(mutate_all(df,toupper))
rename(state, tolower)
merged<-merge(x=newset,y=us_state_info,by.x="state", by.y="state")

head(merged)
view(merged)
library(ggplot2)
storm_plotstorm_plot<-ggplot(state_storms, aes(x=state,y=n))+geom_point(aes(color=region))+labs(x="state",y="# of storm events in 2017")

